= vitepress 源码分析

`Vitepress` 是由 `Vite` 和 `Vue` 驱动的静态站点生成器，通过获取 `Markdown` 编写的内容，并可以生成对应的静态 `HTML` 页面。我们经常使用 `Vitepress` 构建博客等静态网站，本文主要解析一下 `Vitepress` 的实现原理。

== vitepress init 过程分析

根据官方文档推荐，我们执行以下命令初始化项目：

[source, bash]
----
npx vitepress init
----

执行完命令便会进入一个设置界面，通过设置项目名等参数，最终生成一个 `vitepress` 项目。

我们都知道，`npx vitepress init` 实际上等同于：

[source, bash]
----
npm i -g vitepress
vitepress init
----

很好理解，先全局安装 `vitepress`，再执行 `vitepress init` 命令：

=== 源码解析

先通过 `@clack/prompts` 开启命令行 `UI` 界面，用户进行初始化配置：

[source, typescript]
.src/node/init/init.ts
----
import { group } from '@clack/prompts'

const options: ScaffoldOptions = await group(
    {
      root: () =>
        text({
          message: 'Where should VitePress initialize the config?',
          initialValue: './',
          validate(value) {
            // TODO make sure directory is inside
          }
        }),

      title: () =>
        text({
          message: 'Site title:',
          placeholder: 'My Awesome Project'
        }),
    // ...以下省略
)
----

再根据配置项从 `template` 文件夹中拉取模板文件，完成项目的初始化。

== vitepress dev 过程分析

在 `Vitepress` 项目中，我们通过执行以下命令启动开发模式文档服务：

[source, bash]
----
vitepress dev
----

执行完命令，我们便可以在浏览器访问文档网站！

启动服务主要分为两步：

1. 创建 Vite Server；
2. 执行 Vite 插件；

=== 创建 Vite Server

[source, typescript]
.src/node/server.ts
----
import { createServer as createViteServer, type ServerOptions } from 'vite'
import { resolveConfig } from './config'
import { createVitePressPlugin } from './plugin'

export async function createServer(
  root: string = process.cwd(),
  serverOptions: ServerOptions & { base?: string } = {},
  recreateServer?: () => Promise<void>
) {
  // 读取 vitepress 配置
  const config = await resolveConfig(root)

  if (serverOptions.base) {
    config.site.base = serverOptions.base
    delete serverOptions.base
  }

  // 创建 vite 服务
  return createViteServer({
    root: config.srcDir,
    base: config.site.base,
    cacheDir: config.cacheDir,
    plugins: await createVitePressPlugin(config, false, {}, {}, recreateServer),
    server: serverOptions,
    customLogger: config.logger,
    configFile: config.vite?.configFile
  })
}
----

上述代码创建并启动了一个 `Vite` 服务：首先，通过调用 `resolveConfig`，读取用户的 `Vitepress` 配置并整合为一个 `config` 对象（配置路径默认为：`.vitepress/config/index.js`），再将部分配置传入 `createViteServer`，创建并启动 `Vite` 服务。

=== 执行 Vite 插件

看完上面的内容，你可能会有点疑惑，正常来说，`Vite` 需要一个 HTML 作为入口文件，但我们找遍 `Vitepress` 也未发现我们想要的 HTML 文件……其实这部分工作由 `Vite` 插件完成，在上面的代码片段中，我们创建了 `Vite` 服务，同时配置了插件：

[source, typescript]
.src/node/server.ts
----
return createViteServer({
    // 省略代码
    plugins: await createVitePressPlugin(config, false, {}, {}, recreateServer),
    // 省略代码
})
----

`createVitePressPlugin` 函数返回了一个插件列表，其中有一个名为 `vitepress` 的插件：

[source, typescript]
.src/node/plugin.ts
----
const vitePressPlugin: Plugin = {
    name: 'vitepress',
    // 省略代码
    configureServer(server) {
      // 省略代码
      return () => {
        server.middlewares.use(async (req, res, next) => {
          const url = req.url && cleanUrl(req.url)
          if (url?.endsWith('.html')) {
            res.statusCode = 200
            res.setHeader('Content-Type', 'text/html')
            let html = `<!DOCTYPE html>
<html>
  <head>
    <title></title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="description" content="">
  </head>
  <body>
    <div id="app"></div>
    <script type="module" src="/@fs/${APP_PATH}/index.js"></script>
  </body>
</html>`
            html = await server.transformIndexHtml(url, html, req.originalUrl)
            res.end(html)
            return
          }
          next()
        })
      }
    },
    // 省略代码
  }
----

`vitepress` 插件中定义了 `configureServer` 生命周期，并在 `configureServer` 中返回一个 HTML 文件，作为 `Vite` 服务的入口 HTML 文件，当我们访问服务时，浏览器渲染网页，执行 HTML 中引入的 Script 文件（`<script type="module" src="/@fs/${APP_PATH}/index.js"></script>`，其中 `APP_PATH` 为 `src/client/app/index.ts`），网页正常展示在我们眼前，至此，服务正常启动！

=== 文档渲染

在上面的部分，我们整理了启动服务的大致步骤，接下来我们将接着整理 `Markdown` 文件和路由的映射关系！

==== 创建路由

`Vitepress` 并没有使用 `Vuejs` 的官方路由方案（`Vue Router`），而是自己实现了一个简单的路由模块：首先通过监听 `window` 的点击事件，当用户点击超链接元素时，执行跳转函数 `go`：

[source, typescript]
.src/client/app/router.ts
----
async function go(href: string = inBrowser ? location.href : '/') {
    href = normalizeHref(href)
    if ((await router.onBeforeRouteChange?.(href)) === false) return
    updateHistory(href)
    await loadPage(href)
    await router.onAfterRouteChanged?.(href)
}

function updateHistory(href: string) {
    if (inBrowser && normalizeHref(href) !== normalizeHref(location.href)) {
        // save scroll position before changing url
        history.replaceState({ scrollPosition: window.scrollY }, document.title)
        history.pushState(null, '', href)
    }
}
----

通过执行 `updateHistory`，先调用 `history.replaceState`，将当前页面的位置信息 `scrollY` 保存到 `history state` 中；再调用 `history.pushState`，更新 `url`；最后再调用 `loadPage` 加载 `url` 对应的页面，核心代码如下：

[source, typescript]
.src/client/app.ts
----
let pageFilePath = pathToFile(path)
let pageModule = null
// 省略代码
pageModule = import(/*@vite-ignore*/ pageFilePath + '?t=' + Date.now())
// 省略代码
return pageModule
----

`pathToFile` 函数将传入的 url 转成 `md` 后缀的路径，也就是对应的 `Markdown` 文件，再通过 `import` 导入对应路径的文件；举个例子，假设 `url` 为 `/ruofee`，那么最终结果为：`import(/*@vite-ignore*/ 'ruofee.md?t=当前的时间戳')`；

同时监听 `popstate` 事件，当用户使用浏览器返回、前进等操作时，调用 `loadPage` 方法，加载 `url` 对应的 `md` 文件，并根据 `history state` 中保存的页面位置信息进行定位：

[source, typescript]
.src/client/app/router.ts
----
window.addEventListener('popstate', async (e) => {
    await loadPage(
        normalizeHref(location.href),
        (e.state && e.state.scrollPosition) || 0
    )
    router.onAfterRouteChanged?.(location.href)
})

// 省略代码 - loadPage
window.scrollTo(0, scrollPosition)
----

==== 创建 Vue 应用

[source, typescript]
.src/client/app.ts
----
import {
  createApp,
  type App
} from 'vue'

// 省略代码
function newApp(): App {
    // 省略代码
    return createApp(VitePressApp)
}

const app = newApp()
----

首先通过执行 `createApp(VitePressApp)` 创建 `Vue` 应用，`VitePressApp` 是当前主题的 `Layout` 组件（`@theme` 是别名配置，指向当前主题，若是没有设置，则默认为 `src/client/theme-default`）：

[source, typescript]
.src/client/app.ts
----
import RawTheme from '@theme/index'

const Theme = resolveThemeExtends(RawTheme)

const VitePressApp = defineComponent({
    name: 'VitePressApp',
    setup() {
    // 省略代码
        return () => h(Theme.Layout!)
    }
})
----

再将上面的路由对象注册到 `Vue` 应用中，并注册两个全局组件：`Content` 和 `ClientOnly`：

[source,typescript]
.src/client/app.ts
----
// 将路由注入 app
app.provide(RouterSymbol, router)
const data = initData(router.route)
app.provide(dataSymbol, data)

// 注册全局组件
app.component('Content', Content)
app.component('ClientOnly', ClientOnly)
----

==== Markdown 渲染

直到目前为止，我们已经启动了 `Vite` 服务，我们可以在浏览器中访问 HTML，并执行 Script 创建 `Vue` 应用，实现了路由系统，当我们访问对应链接时，便会加载对应的 Markdown 文件，但你肯定会有疑惑：我们的 Markdown 文件如何被解析渲染到页面中呢？

其实在启动服务的部分中，我们提到了一个名为 `vitepress` 的 `vite` 插件，Markdown 渲染工作便是在这个插件的 `transform` 生命周期中实现：

[source, typescript]
.src/node/plugin.ts
----
{
    async transform(code, id) {
        if (id.endsWith('.vue')) {
            return processClientJS(code, id)
        } else if (id.endsWith('.md')) {
            // transform .md files into vueSrc so plugin-vue can handle it
            const { vueSrc, deadLinks, includes } = await markdownToVue(
              code,
              id,
              config.publicDir
            )
            // 省略代码
            const res = processClientJS(vueSrc, id)
            return res
        }
    }
}
----

当我们使用 `import` 加载 `md` 文件时，便会调用 `transform` 函数，对文件内容进行转换：执行 `markdownToVue`，将 `markdown` 内容转成 Vue SFC，再通过 `@vitejs/plugin-vue` 插件将 `Vue` 组件渲染到页面；那么 `markdownToVue` 做了什么工作呢？具体如下：

[source, typescript]
.src/node/markdownToVue.ts
----
const html = md.render(src, env)
const vueSrc = [
    // 省略代码
    `<template><div>${html}</div></template>`,
    // 省略代码
].join('\n')
----

这部分比较简单，`md` 是一个 `markdown-it` 对象，通过调用 `md.render` 函数，将 `markdown` 内容转成 HTML 格式，再输出到页面；

值得一提的是，若是你在 `markdown` 中书写 `Vue` 组件语法，由于是非 `markdown` 语法，因此 `markdown-it` 不会对其进行转换，那么 `Vue` 语法将在页面中得以执行，官网中的例子便是利用这个原理！

== vitepress build 过程分析

[source, typescript]
.src/node/cli.ts
----
if (command === 'build') { // 构建用于生产环境的 VitePress 站点
    build(root, argv).catch((err) => {
      createLogger().error(
        `${c.red(`build error:`)}\n${err.message}\n${err.stack}`
      )
      process.exit(1)
    })
}
----

[source, typescript]
.src/node/build/build.ts
----
/**
 * 它处理了整个构建过程，包括配置处理、打包、渲染页面、生成资源文件等
 * @param root
 * @param buildOptions
 */
export async function build(
  root?: string,
  buildOptions: BuildOptions & { base?: string; mpa?: string } = {}
) {
  const start = Date.now() // 获取当前时间戳，记录构建开始时间。now() 静态方法返回自 epoch 以来经过的毫秒数

  process.env.NODE_ENV = 'production' // 设置为生产环境
  // 解析并获取构建所需的配置。它会加载生产环境的构建配置
  const siteConfig = await resolveConfig(root, 'build', 'production')
  const unlinkVue = linkVue()

  // 处理构建选项
  if (buildOptions.base) { // 设置站点的基础路径
    siteConfig.site.base = buildOptions.base
    delete buildOptions.base
  }

  if (buildOptions.mpa) { // 如果设置为 true，则启用多页面应用（MPA）模式
    siteConfig.mpa = true
    delete buildOptions.mpa
  }

  if (buildOptions.outDir) { // 设置构建输出目录
    siteConfig.outDir = path.resolve(process.cwd(), buildOptions.outDir)
    delete buildOptions.outDir
  }

  try {
    // 执行实际的打包操作
    // clientResult：客户端打包结果
    // serverResult：服务器端打包结果
    // pageToHashMap：页面与哈希值的映射
    const { clientResult, serverResult, pageToHashMap } = await bundle(
      siteConfig,
      buildOptions
    )

    if (process.env.BUNDLE_ONLY) {
      return
    }

    // 通过 import 动态加载 app.js，它是渲染页面所需的入口文件
    const entryPath = path.join(siteConfig.tempDir, 'app.js')
    const { render } = await import(
      pathToFileURL(entryPath).toString() + '?t=' + Date.now()
    )

    // 这段代码主要处理网站页面的渲染，具体来说是通过异步任务来生成网站页面，并为每个页面添加合适的资源（如 CSS 和 JavaScript）。
    // 在这个过程中，默认主题的字体会被特殊处理，且每个页面都会被渲染成最终的 HTML 文件
    await task('rendering pages', async () => {
      // clientResult.output.find() 查找 clientResult 中的输出项，找到类型为 chunk 且是入口文件（isEntry）的 JavaScript 文件。
      // 这是用于渲染页面的核心 JavaScript 代码
      const appChunk =
        clientResult &&
        (clientResult.output.find(
          (chunk) =>
            chunk.type === 'chunk' &&
            chunk.isEntry &&
            chunk.facadeModuleId?.endsWith('.js')
        ) as Rollup.OutputChunk)

      // 查找 CSS 文件。在 MPA（多页面应用）模式下，优先使用 serverResult，否则使用 clientResult 中的 CSS 文件
      const cssChunk = (
        siteConfig.mpa ? serverResult : clientResult!
      ).output.find(
        (chunk) => chunk.type === 'asset' && chunk.fileName.endsWith('.css')
      ) as Rollup.OutputAsset

      // 过滤出所有类型为 asset 且不是 CSS 的静态资源（例如 JavaScript、图片等）。
      // 然后将资源的文件名与基础路径 (siteConfig.site.base) 拼接，得到资源的完整路径
      const assets = (siteConfig.mpa ? serverResult : clientResult!).output
        .filter(
          (chunk) => chunk.type === 'asset' && !chunk.fileName.endsWith('.css')
        )
        .map((asset) => siteConfig.site.base + asset.fileName)

      // default theme special handling: inject font preload
      // custom themes will need to use `transformHead` to inject this
      // additionalHeadTags 是一个数组，用来存储将在 HTML 页头注入的额外标签（例如预加载字体）
      const additionalHeadTags: HeadConfig[] = []
      // 判断当前是否使用默认主题。如果 clientResult 中包含名为 'theme' 的 chunk，并且该 chunk 中包含 client/theme-default 模块，则认为使用的是默认主题
      const isDefaultTheme =
        clientResult &&
        clientResult.output.some(
          (chunk) =>
            chunk.type === 'chunk' &&
            chunk.name === 'theme' &&
            chunk.moduleIds.some((id) => id.includes('client/theme-default'))
        )

      const metadataScript = generateMetadataScript(pageToHashMap, siteConfig)

      // 如果使用的是默认主题且找到了字体文件（匹配 inter-roman-latin 字体文件），则将该字体文件作为 preload 资源注入到 HTML 的 <head> 中
      if (isDefaultTheme) {
        const fontURL = assets.find((file) =>
          /inter-roman-latin\.\w+\.woff2/.test(file)
        )
        if (fontURL) {
          additionalHeadTags.push([
            'link',
            {
              rel: 'preload',
              href: fontURL,
              as: 'font',
              type: 'font/woff2',
              crossorigin: ''
            }
          ])
        }
      }

      // 使用 pMap 执行并发渲染多个页面。pMap 是一个并发执行的映射函数，它会并行处理 siteConfig.pages 中的每个页面和 404.md 页面
      await pMap(
        ['404.md', ...siteConfig.pages],
        async (page) => {
          // 对于每个页面，调用 renderPage 函数来进行页面渲染
          await renderPage(
            render, // 渲染函数
            siteConfig, // 网站配置
            siteConfig.rewrites.map[page] || page, // 页面路径（如果有重写规则则使用重写后的路径）
            clientResult, // 客户端打包结果
            appChunk, // 入口 JS
            cssChunk, // CSS
            assets, // 静态资源
            pageToHashMap, // 页面与哈希值的映射
            metadataScript, // 元数据脚本（可能用于 SEO 或页面级别的配置）
            additionalHeadTags // 需要注入页面的额外头部标签
          )
        },
        { concurrency: siteConfig.buildConcurrency }
      )
    })

    // emit page hash map for the case where a user session is open
    // when the site got redeployed (which invalidates current hash map)
    fs.writeJSONSync( // 将 pageToHashMap（页面与哈希的映射关系）写入 hashmap.json 文件
      path.join(siteConfig.outDir, 'hashmap.json'),
      pageToHashMap
    )
  } finally {
    unlinkVue()
    if (!process.env.DEBUG) await rimraf(siteConfig.tempDir) // 如果不是调试模式，删除临时构建目录
  }

  await generateSitemap(siteConfig) // 生成站点地图
  await siteConfig.buildEnd?.(siteConfig) // 调用 buildEnd 钩子（如果存在），标记构建结束
  clearCache() // 清理缓存

  // 输出构建完成时间
  siteConfig.logger.info(
    `build complete in ${((Date.now() - start) / 1000).toFixed(2)}s.`
  )
}
----

[source, typescript]
.src/node/build/bundle.ts
----
/**
 * VitePress 项目构建过程中的一个核心函数，它负责为客户端和服务器分别构建相应的捆绑文件，并生成页面哈希映射。
 * 它的作用是处理多入口的构建，其中每个页面都是一个入口模块，并且根据是否启用了多页面应用（MPA）模式来分别处理客户端和服务器端的构建。
 * @param config VitePress 项目的配置，包含页面路径、主题目录、构建目录等信息
 * @param options 构建选项，包括 Vite 配置、Rollup 配置等
 */
export async function bundle(
  config: SiteConfig,
  options: BuildOptions
): Promise<{
  clientResult: Rollup.RollupOutput | null
  serverResult: Rollup.RollupOutput
  pageToHashMap: Record<string, string>
}> {
  const pageToHashMap = Object.create(null)
  const clientJSMap = Object.create(null)

  // define custom rollup input
  // this is a multi-entry build - every page is considered an entry chunk
  // the loading is done via filename conversion rules so that the
  // metadata doesn't need to be included in the main chunk.
  // 定义自定义的 Rollup 输入
  // 这是一个多入口构建——每个页面都被视为一个入口块
  // 加载是通过文件名转换规则完成的，因此元数据不需要包含在主块中。
  const input: Record<string, string> = {}
  // 首先会为每个页面创建一个输入文件，将页面路径转换为符合规范的文件名。输入文件会包含所有页面，作为 Rollup 构建的多入口文件
  config.pages.forEach((file) => {
    // page filename conversion
    // foo/bar.md -> foo_bar.md
    const alias = config.rewrites.map[file] || file
    input[slash(alias).replace(/\//g, '_')] = path.resolve(config.srcDir, file)
  })

  // 创建一个正则表达式 (themeEntryRE)，用于匹配主题相关的入口文件（index.js 或 index.ts）的路径
  // 正则表达式 themeEntryRE 会匹配 config.themeDir 目录下的 index.js 或 index.ts 文件，以及它们可能的模块化变体（例如 .mjs 或 .mts）
  const themeEntryRE = new RegExp(
    `^${escapeRegExp(
        // 该部分将 config.themeDir 目录与 'index.js' 文件名拼接，得到主题目录下的 index.js 文件的绝对路径
      path.resolve(config.themeDir, 'index.js').replace(/\\/g, '/')
    ).slice(0, -2)}m?(j|t)s`
  )

  // resolve options to pass to vite
  const { rollupOptions } = options

  // 使用 resolveViteConfig 函数来解析并生成 Vite 配置，分别用于 SSR（服务器端渲染）和客户端构建
  const resolveViteConfig = async (
    ssr: boolean
  ): Promise<ViteInlineConfig> => ({
    root: config.srcDir,
    cacheDir: config.cacheDir,
    base: config.site.base,
    logLevel: config.vite?.logLevel ?? 'warn',
    plugins: await createVitePressPlugin(
      config,
      ssr,
      pageToHashMap,
      clientJSMap
    ),
    ssr: {
      noExternal: ['vitepress', '@docsearch/css']
    },
    build: {
      ...options,
      emptyOutDir: true,
      ssr,
      ssrEmitAssets: config.mpa,
      // minify with esbuild in MPA mode (for CSS)
      minify: ssr
        ? config.mpa
          ? 'esbuild'
          : false
        : typeof options.minify === 'boolean'
          ? options.minify
          : !process.env.DEBUG,
      // 决定是否构建服务器端渲染（SSR）版本，ssr: true 表示构建 SSR，ssr: false 则为客户端构建
      outDir: ssr ? config.tempDir : config.outDir,
      cssCodeSplit: false,
      rollupOptions: {
        ...rollupOptions,
        input: {
          ...input, // 指定入口文件
          // use different entry based on ssr or not
          app: path.resolve(APP_PATH, ssr ? 'ssr.js' : 'index.js')
        },
        // important so that each page chunk and the index export things for each
        // other
        preserveEntrySignatures: 'allow-extension',
        output: {
          sanitizeFileName,
          ...rollupOptions?.output,
          assetFileNames: `${config.assetsDir}/[name].[hash].[ext]`,
          ...(ssr
            ? {
                entryFileNames: '[name].js',
                chunkFileNames: '[name].[hash].js'
              }
            : {
                entryFileNames: `${config.assetsDir}/[name].[hash].js`,
                chunkFileNames(chunk) {
                  // avoid ads chunk being intercepted by adblock
                  return /(?:Carbon|BuySell)Ads/.test(chunk.name)
                    ? `${config.assetsDir}/chunks/ui-custom.[hash].js`
                    : `${config.assetsDir}/chunks/[name].[hash].js`
                },
                // 用于将一些模块（例如框架代码）分离到单独的文件中，从而避免由于自定义主题的修改导致所有页面的哈希值变化
                manualChunks(id, ctx) {
                  // move known framework code into a stable chunk so that
                  // custom theme changes do not invalidate hash for all pages
                  if (id.startsWith('\0vite')) {
                    return 'framework'
                  }
                  if (id.includes('plugin-vue:export-helper')) {
                    return 'framework'
                  }
                  if (
                    id.includes(`${clientDir}/app`) &&
                    id !== `${clientDir}/app/index.js`
                  ) {
                    return 'framework'
                  }
                  if (
                    isEagerChunk(id, ctx.getModuleInfo) &&
                    /@vue\/(runtime|shared|reactivity)/.test(id)
                  ) {
                    return 'framework'
                  }

                  if (
                    (id.startsWith(`${clientDir}/theme-default`) ||
                      !excludedModules.some((i) => id.includes(i))) &&
                    staticImportedByEntry(
                      id,
                      ctx.getModuleInfo,
                      cacheTheme,
                      themeEntryRE
                    )
                  ) {
                    return 'theme'
                  }
                }
              })
        }
      }
    },
    configFile: config.vite?.configFile
  })

  let clientResult!: Rollup.RollupOutput | null
  let serverResult!: Rollup.RollupOutput

  // 为客户端和服务器端执行构建
  // 客户端构建：非 MPA 模式下，构建客户端的捆绑文件（clientResult）。
  // 服务器端构建：无论是否为 MPA，都会构建服务器端的捆绑文件（serverResult）
  await task('building client + server bundles', async () => {
    clientResult = config.mpa
      ? null
      : ((await build(await resolveViteConfig(false))) as Rollup.RollupOutput)
    serverResult = (await build(
      await resolveViteConfig(true)
    )) as Rollup.RollupOutput
  })

  // 处理 MPA 模式
  // 是否启用多页面应用模式。如果启用了 MPA，每个页面都会有一个独立的捆绑文件，并且服务器端捆绑会处理非 JS 的静态资源
  if (config.mpa) {
    // in MPA mode, we need to copy over the non-js asset files from the
    // server build since there is no client-side build.
    // 在 MPA 模式下，客户端构建被跳过，因为客户端的捆绑是通过静态文件生成的
    await Promise.all(
      serverResult.output.map(async (chunk) => {
        // 服务器端的非 .js 资源（例如 .css 或其他静态资源）会从临时构建目录复制到最终的输出目录
        if (!chunk.fileName.endsWith('.js')) {
          const tempPath = path.resolve(config.tempDir, chunk.fileName)
          const outPath = path.resolve(config.outDir, chunk.fileName)
          await fs.copy(tempPath, outPath)
        }
      })
    )
    // also copy over public dir 如果存在公共目录（public），则会将其中的文件复制到输出目录
    const publicDir = path.resolve(config.srcDir, 'public')
    if (fs.existsSync(publicDir)) {
      await fs.copy(publicDir, config.outDir)
    }
    // build <script client> bundle
    // 对于客户端 JS 文件，如果有对应的客户端捆绑文件（clientJSMap），会调用 buildMPAClient 构建客户端部分
    if (Object.keys(clientJSMap).length) {
      clientResult = await buildMPAClient(clientJSMap, config)
    }
  }

  // clientResult：客户端构建结果，包含客户端捆绑输出。MPA 模式下可能为 null。
  // serverResult：服务器端构建结果，包含服务器捆绑输出。
  // pageToHashMap：一个记录页面路径和页面哈希值的映射表。
  return { clientResult, serverResult, pageToHashMap }
}
----


== 参考

* https://vitepress.dev[文档]
